width = 1920
height = 1080

time_suffix = "d"

title = "Time Plan"

[style]
# All of these are optional
font_colour = "#333333"
divider_minor_colour = "#cccccc"

divider_minor_width = 2 # Pixels
divider_major_colour = "#aaaaaa"
divider_major_width = 5 # Pixels

margin_main = 25
padding_main = 25
margin_title_bottom = 25

padding_task = 10

bg_task_colour = "rgba(200, 200, 200, 0.5)"
bg_task_colour_alternate = "rgba(200, 200, 200, 0.25)"
