width = 1920
height = 1080

time_suffix = "d"


[style]
# All of these are optional
font_colour = "#333333"
divider_minor_colour = "#cccccc"

divider_minor_width = 2 # Pixels
divider_major_colour = "#aaaaaa"
divider_major_width = 5 # Pixels

border_main = 25
